parameters:
#    elephantly_resource.example.class: elephantly\ResourceBundle\Example

services:
#    elephantly_resource.example:
#        class: %elephantly_resource.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
