parameters:
   elephantly.factory.repository.class: Elephantly\ResourceBundle\Doctrine\Factory\RepositoryFactory

services:
   elephantly.factory.repository:
       class: %elephantly.factory.repository.class%
    #    arguments: [@doctrine.orm.entity_manager, %parameter%]
